package com.android.universities.common.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "universities")
data class University(
    // Having a primary key is mandatory for Room entities.
    // Since none of the fields in the University class guarantee uniqueness,
    // using an autogenerated integer primary key ensures each entry has a unique identifier,
    // which simplifies data management and operations.
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val state: String?,
    val country: String,
    val countryCode: String,
    val webPage: String?,
)